- name: init kubernetes master
  command: >
    kubeadm init
    --kubernetes-version={{ k8s_version }}
    --pod-network-cidr=10.244.0.0/16
    --service-cidr=10.96.0.0/12
    --token={{ k8s_token }}
    --skip-token-print
    --apiserver-cert-extra-sans={{ k8s_ext_host }}
    {% for ip in ansible_all_ipv4_addresses %}--apiserver-cert-extra-sans={{ ip }} {% endfor %}
    {% for ip in ansible_all_ipv6_addresses %}--apiserver-cert-extra-sans={{ ip }} {% endfor %}
  args:
    creates: /etc/kubernetes/admin.conf

- name: create ~/.kube directory for root
  file:
    path: /root/.kube
    state: directory

- name: symlink /etc/kubernetes/admin.conf -> ~/.kube/config
  file:
    path: /root/.kube/config
    src: /etc/kubernetes/admin.conf
    state: link

- name: install flannel as an overlay network
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
  args:
    creates: /etc/cni/net.d/10-flannel.conf
